version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    # volumes:
    #   - ./backend:/app
    environment:
      - GO_ENV=development
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    restart: always
